#!/usr/bin/env python3
"""
Interactive setup wizard for Book Research MCP.

Guides users through configuration and validates paths.
"""

import json
import os
import sqlite3
import sys
from pathlib import Path


def main():
    print("=" * 60)
    print("🔧 Book Research MCP - Setup Wizard")
    print("=" * 60)
    print()

    # Check for existing .env
    if Path(".env").exists():
        print("⚠️  .env file already exists.")
        overwrite = input("Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Setup cancelled.")
            return
        print()

    # Get Zotero path
    print("📚 ZOTERO CONFIGURATION")
    print("-" * 60)
    print("Find your Zotero data directory:")
    print("  • macOS:   ~/Zotero")
    print("  • Linux:   ~/Zotero")
    print("  • Windows: C:\\Users\\<username>\\Zotero")
    print()

    zotero_path = input("Zotero data path: ").strip()
    zotero_path = os.path.expanduser(zotero_path)

    if not os.path.exists(zotero_path):
        print(f"❌ Path not found: {zotero_path}")
        print("   Please check the path and try again.")
        return

    # Check for zotero.sqlite
    zotero_db = os.path.join(zotero_path, "zotero.sqlite")
    if not os.path.exists(zotero_db):
        print(f"❌ zotero.sqlite not found in {zotero_path}")
        print("   Make sure this is your Zotero data directory, not the application.")
        return

    print("✅ Zotero database found")
    print()

    # Get Scrivener path
    print("📝 SCRIVENER CONFIGURATION")
    print("-" * 60)
    print("Find your Scrivener project (.scriv bundle):")
    print("  • macOS:   ~/Documents or ~/Dropbox/Apps/Scrivener")
    print("  • Windows: C:\\Users\\<username>\\Documents")
    print()

    scrivener_path = input("Scrivener project path (.scriv): ").strip()
    scrivener_path = os.path.expanduser(scrivener_path)

    if not os.path.exists(scrivener_path):
        print(f"❌ Path not found: {scrivener_path}")
        print("   Please check the path and try again.")
        return

    if not scrivener_path.endswith(".scriv"):
        print("⚠️  Warning: Path doesn't end in .scriv")
        confirm = input("Continue anyway? (y/N): ").strip().lower()
        if confirm != "y":
            return

    # Check for Files/Data directory
    scrivener_data = os.path.join(scrivener_path, "Files", "Data")
    if not os.path.exists(scrivener_data):
        print(f"⚠️  Warning: Files/Data directory not found in {scrivener_path}")
        print("   This may not be a valid Scrivener project.")
        confirm = input("Continue anyway? (y/N): ").strip().lower()
        if confirm != "y":
            return

    print("✅ Scrivener project found")
    print()

    # Embedding model choice
    print("🧠 EMBEDDING MODEL")
    print("-" * 60)
    print("Choose an embedding model:")
    print("  1. all-mpnet-base-v2 (Best quality, requires GPU)")
    print("  2. all-MiniLM-L6-v2 (Fast, CPU-friendly)")
    print("  3. paraphrase-multilingual-MiniLM-L12-v2 (Multi-language)")
    print()

    model_choice = input("Choice (1-3) [1]: ").strip() or "1"

    models = {
        "1": "all-mpnet-base-v2",
        "2": "all-MiniLM-L6-v2",
        "3": "paraphrase-multilingual-MiniLM-L12-v2",
    }

    embedding_model = models.get(model_choice, "all-mpnet-base-v2")
    print(f"Selected: {embedding_model}")
    print()

    # Create .env
    print("💾 CREATING CONFIGURATION FILES")
    print("-" * 60)

    env_content = f"""# Book Research MCP Configuration
# Generated by setup.py

# Zotero data directory
ZOTERO_DATA_PATH={zotero_path}

# Scrivener project
SCRIVENER_PROJECT_PATH={scrivener_path}

# Embedding model
EMBEDDING_MODEL={embedding_model}

# Vector database storage (local directory)
VECTORDB_PATH=./data/vectordb

# Debug logging (set to true for troubleshooting)
DEBUG=false
"""

    with open(".env", "w") as f:
        f.write(env_content)

    print("✅ Created .env file")

    # Offer to create config.local.json
    print()
    create_local = (
        input("Create project-specific config (config.local.json)? (Y/n): ")
        .strip()
        .lower()
    )

    if create_local != "n":
        project_name = input("  Project/book name: ").strip() or "My Book"
        author_name = input("  Your name: ").strip() or "Author"

        # Try to detect Zotero collections
        print()
        print("🔍 Scanning Zotero collections...")

        try:
            collections = scan_zotero_collections(zotero_db)
            print(f"   Found {len(collections)} collections")

            if collections:
                print()
                print("   Top-level collections:")
                for i, col in enumerate(collections[:10], 1):
                    print(f"     {i}. {col}")
        except Exception as e:
            print(f"   ⚠️  Couldn't scan collections: {e}")
            collections = []

        print()
        root_collection = input(
            "  Root collection name (or press Enter to skip): "
        ).strip()

        local_config = {"project": {"name": project_name, "author": author_name}}

        if root_collection:
            chapter_pattern = (
                input("  Chapter number pattern [^(\\d+)\\.]: ").strip() or "^(\\d+)\\."
            )

            local_config["zotero"] = {
                "root_collection": root_collection,
                "chapter_pattern": chapter_pattern,
                "exclude_collections": ["_incoming", "__incoming", "Archive"],
            }

        local_config["scrivener"] = {
            "draft_folder": "Manuscript",
            "research_folder": "Research",
        }

        # Ask about chapter structure
        print()
        print("  Define your book structure (optional):")
        define_structure = input("  Define parts and chapters? (y/N): ").strip().lower()

        if define_structure == "y":
            structure = []
            part_num = 1

            while True:
                part_name = input(
                    f"    Part {part_num} name (or Enter to finish): "
                ).strip()
                if not part_name:
                    break

                chapters_input = input(
                    "    Chapter numbers (e.g., 1,2,3 or 1-5): "
                ).strip()

                # Parse chapter range
                chapters = parse_chapter_range(chapters_input)

                if chapters:
                    structure.append({"part": part_name, "chapters": chapters})
                    part_num += 1

            if structure:
                local_config["chapters"] = {"structure": structure}

        with open("config.local.json", "w") as f:
            json.dump(local_config, f, indent=2)

        print("✅ Created config.local.json")

    # Create data directories
    os.makedirs("data/vectordb", exist_ok=True)
    os.makedirs("data/logs", exist_ok=True)
    print("✅ Created data directories")

    # Final instructions
    print()
    print("=" * 60)
    print("🎉 Setup complete!")
    print("=" * 60)
    print()
    print("Next steps:")
    print()
    print("1. Start the service:")
    print("   $ docker compose up --build -d")
    print()
    print("2. Check logs:")
    print("   $ docker compose logs -f")
    print()
    print("3. Test in Claude Code (from project directory):")
    print("   $ claude")
    print("   > Get indexing status")
    print()
    print("   Note: MCP server is pre-configured in .claude/config.json")
    print()
    print("📖 See README.md for usage examples")
    print()


def scan_zotero_collections(db_path: str) -> list:
    """Scan Zotero database for top-level collection names"""
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        cursor.execute("""
            SELECT collectionName
            FROM collections
            WHERE parentCollectionID IS NULL
            ORDER BY collectionName
        """)

        collections = [row[0] for row in cursor.fetchall()]
        conn.close()

        return collections
    except Exception as e:
        raise Exception(f"Database query failed: {e}")


def parse_chapter_range(input_str: str) -> list:
    """Parse chapter range like '1,2,3' or '1-5' into list of integers"""
    try:
        chapters = []

        # Split by comma
        parts = input_str.split(",")

        for part in parts:
            part = part.strip()

            # Check for range (1-5)
            if "-" in part:
                start, end = part.split("-")
                start = int(start.strip())
                end = int(end.strip())
                chapters.extend(range(start, end + 1))
            else:
                # Single number
                chapters.append(int(part))

        return sorted(list(set(chapters)))  # Remove duplicates and sort
    except Exception:
        return []


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        sys.exit(1)
